### ISSUE TITLE
 Error: /home/dvws-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header

### ISSUE THREAD

**Issue by suhas-s-dev** [snoopysecurity/dvws-node#10]
I keep getting this when I am trying to run docker compose:
 Error: /home/dvws-node/node_modules/bcrypt/lib/binding/bcrypt_lib.node: invalid ELF header
web_1         |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
web_1         |     at Module.load (internal/modules/cjs/loader.js:653:32)
web_1         |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
web_1         |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
web_1         |     at Module.require (internal/modules/cjs/loader.js:692:17)
web_1         |     at require (internal/modules/cjs/helpers.js:25:18)
web_1         |     at Object.<anonymous> (/home/dvws-node/node_modules/bcrypt/bcrypt.js:6:16)
web_1         |     at Module._compile (internal/modules/cjs/loader.js:778:30)
web_1         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
web_1         |     at Module.load (internal/modules/cjs/loader.js:653:32)
web_1         |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
web_1         |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
web_1         |     at Module.require (internal/modules/cjs/loader.js:692:17)
web_1         |     at require (internal/modules/cjs/helpers.js:25:18)
web_1         |     at Object.<anonymous> (/home/dvws-node/models/users.js:2:16)
web_1         |     at Module._compile (internal/modules/cjs/loader.js:778:30)
web_1         | [nodemon] app crashed - waiting for file changes before starting...

Could you kindly suggest any fixes? Thank you..

**Comment by snoopysecurity** [comment]
I think this issue is mentioned here: https://stackoverflow.com/questions/32105251/bcrypt-invalid-elf-header-with-docker-and-sails-js

so if you tried to install manually before and then run `docker-compose`, the node_modules files are copied, i've added a dockerignore file. Can you clone dvws-node and try again?

**Comment by fusionsec** [comment]
Sorry for the delayed response.

I'm getting the same error with one new addition being token expiration:

XML-RPC server listening on port 9090
API listening at :80, go to http://dvws.local (127.0.0.1)
(node:4566) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: TokenExpiredError: jwt expired
    at validateToken (/root/dvws-node/utils.js:18:15)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dvws-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/dvws-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at /root/dvws-node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
    at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/dvws-node/node_modules/express/lib/router/index.js:174:3)
    at router (/root/dvws-node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/dvws-node/node_modules/express/lib/router/index.js:317:13)
    at /root/dvws-node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
    at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
    at cors (/root/dvws-node/node_modules/cors/lib/index.js:188:7)
Error: TokenExpiredError: jwt expired
    at validateToken (/root/dvws-node/utils.js:18:15)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dvws-node/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/dvws-node/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at /root/dvws-node/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
    at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/dvws-node/node_modules/express/lib/router/index.js:174:3)
    at router (/root/dvws-node/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/dvws-node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/dvws-node/node_modules/express/lib/router/index.js:317:13)
    at /root/dvws-node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/dvws-node/node_modules/express/lib/router/index.js:335:12)
    at next (/root/dvws-node/node_modules/express/lib/router/index.js:275:10)
    at cors (/root/dvws-node/node_modules/cors/lib/index.js:188:7)
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/root/dvws-node/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/root/dvws-node/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/root/dvws-node/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
[nodemon] app crashed - waiting for file changes before starting...


Thanks again for your assistance.

**Comment by snoopysecurity** [comment]
Closing due to inactivity
